# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atempoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atempo',
            name='years',
            field=models.IntegerField(null=True),
        ),
    ]
